create or replace table CUSTOMER (
    C_CUSTKEY NUMBER,
    C_NAME STRING,
    C_ADDRESS STRING,
    C_NATIONKEY NUMBER,
    C_PHONE STRING,
    C_ACCTBAL NUMBER,
    C_MKTSEGMENT STRING,
    C_COMMENT STRING
);