name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run deploy script
        working-directory: my_snowflake_project
        run: |
          source /home/rabinjais7/python_projects/snowflake_cicd/.venv/bin/activate
          ENV=${{ github.ref_name }}
          [ "$ENV" = "main" ] && ENV=dev
          echo "Deploying to environment: $ENV"
          ./deploy.sh $ENV
